services:
    nginx:
      env_file:
        - .env
      image: mobidevpublisher/nginx:stable
      restart: on-failure
      environment:
          NGINX_PREDEFINED_TEMPLATE: "laravel.conf.template"
          NGINX_SERVER_NAME: "localhost"
          NGINX_PORT: 8080
          NGINX_ROOT: /var/www/app/public
          PHP_HOST: php
          PHP_PORT: 9000
      working_dir: /var/www/app/
      volumes:
          - ".:/var/www/app/"
      networks:
          - local
      depends_on:
          - php
      ports:
          - "8080:8080"
      expose:
          - "8080"
    php:
      env_file:
        - .env
      working_dir: /var/www/app/
      image: mobidevpublisher/php:8.1
      restart: on-failure
      environment:
          PHP_ENABLED_EXTENSIONS: "amqp apcu sodium redis zip pdo_pgsql gd gmp"
          PHP_ALLOW_URL_FOPEN: "On"
          PHP_MAX_EXECUTION_TIME: 60
          PHP_MAX_INPUT_TIME: 60
          PHP_MEMORY_LIMIT: "128M"
          PHP_POST_MAX_SIZE: "120M"
          PHP_UPLOAD_MAX_FILESIZE: "100M"
          PHP_SHORT_OPEN_TAG: "On"
          PHP_DISPLAY_ERRORS: "On"
          PHP_DISPLAY_STARTUP_ERRORS: "On"
      volumes:
          - ".:/var/www/app/"
      networks:
          - local
    postgres:
      env_file:
        - .env
      image: postgres:13.2
      restart: on-failure
      environment:
          POSTGRES_USER: ${POSTGRES_USER}
          POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
          POSTGRES_DB: ${POSTGRES_DB}
      volumes:
          - "dbdata:/var/lib/postgresql/data"
      networks:
          - local
    mysql:
      image: mysql:latest
      restart: on-failure
      environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
        MYSQL_DATABASE: ${MYSQL_DB}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      volumes:
        - "mysqldata:/var/lib/mysql"
      ports:
        - "3306:3306"
      networks:
        - local
    adminer:
      image: adminer:4.8.1
      restart: always
      environment:
          ADMINER_DESIGN: nette
      ports:
          - 8084:8080
      networks:
          - local

networks:
    local:
      name: local

volumes:
    appdata:
        driver: local
    dbdata:
        driver: local
    mysqldata:
      driver: local
